#! /bin/sh
set -e

write_cache()
{
if [ -x /usr/bin/gtk-update-icon-cache-3.0 ]; then
    if ! gtk-update-icon-cache-3.0 --force --quiet /usr/share/icons/Faba; then
        echo "WARNING: icon cache generation failed"
    fi
fi
}

if [ "$1" = "triggered" ]; then
    write_cache
    exit 0
fi

if [ -x /usr/lib/icon-naming-utils/icon-name-mapping ]; then
	echo 'Performing icon mapping...'
	cd /usr/share/icons/Faba/16x16/
	/usr/lib/icon-naming-utils/icon-name-mapping -c actions
	/usr/lib/icon-naming-utils/icon-name-mapping -c animations
	/usr/lib/icon-naming-utils/icon-name-mapping -c apps
	/usr/lib/icon-naming-utils/icon-name-mapping -c categories
	/usr/lib/icon-naming-utils/icon-name-mapping -c devices
	/usr/lib/icon-naming-utils/icon-name-mapping -c mimetypes
	/usr/lib/icon-naming-utils/icon-name-mapping -c emblems
	/usr/lib/icon-naming-utils/icon-name-mapping -c panel
	/usr/lib/icon-naming-utils/icon-name-mapping -c places
	/usr/lib/icon-naming-utils/icon-name-mapping -c status
	cd /usr/share/icons/Faba/24x24/
	/usr/lib/icon-naming-utils/icon-name-mapping -c actions
	/usr/lib/icon-naming-utils/icon-name-mapping -c animations
	/usr/lib/icon-naming-utils/icon-name-mapping -c apps
	/usr/lib/icon-naming-utils/icon-name-mapping -c categories
	/usr/lib/icon-naming-utils/icon-name-mapping -c devices
	/usr/lib/icon-naming-utils/icon-name-mapping -c mimetypes
	/usr/lib/icon-naming-utils/icon-name-mapping -c emblems
	/usr/lib/icon-naming-utils/icon-name-mapping -c panel
	/usr/lib/icon-naming-utils/icon-name-mapping -c places
	/usr/lib/icon-naming-utils/icon-name-mapping -c status
	cd /usr/share/icons/Faba/32x32/
	/usr/lib/icon-naming-utils/icon-name-mapping -c actions
	/usr/lib/icon-naming-utils/icon-name-mapping -c animations
	/usr/lib/icon-naming-utils/icon-name-mapping -c apps
	/usr/lib/icon-naming-utils/icon-name-mapping -c categories
	/usr/lib/icon-naming-utils/icon-name-mapping -c devices
	/usr/lib/icon-naming-utils/icon-name-mapping -c mimetypes
	/usr/lib/icon-naming-utils/icon-name-mapping -c emblems
	/usr/lib/icon-naming-utils/icon-name-mapping -c panel
	/usr/lib/icon-naming-utils/icon-name-mapping -c places
	/usr/lib/icon-naming-utils/icon-name-mapping -c status
	cd /usr/share/icons/Faba/48x48/
	/usr/lib/icon-naming-utils/icon-name-mapping -c actions
	/usr/lib/icon-naming-utils/icon-name-mapping -c animations
	/usr/lib/icon-naming-utils/icon-name-mapping -c apps
	/usr/lib/icon-naming-utils/icon-name-mapping -c categories
	/usr/lib/icon-naming-utils/icon-name-mapping -c devices
	/usr/lib/icon-naming-utils/icon-name-mapping -c mimetypes
	/usr/lib/icon-naming-utils/icon-name-mapping -c emblems
	/usr/lib/icon-naming-utils/icon-name-mapping -c panel
	/usr/lib/icon-naming-utils/icon-name-mapping -c places
	/usr/lib/icon-naming-utils/icon-name-mapping -c status
	cd /usr/share/icons/Faba/64x64/
	/usr/lib/icon-naming-utils/icon-name-mapping -c actions
	/usr/lib/icon-naming-utils/icon-name-mapping -c animations
	/usr/lib/icon-naming-utils/icon-name-mapping -c apps
	/usr/lib/icon-naming-utils/icon-name-mapping -c categories
	/usr/lib/icon-naming-utils/icon-name-mapping -c devices
	/usr/lib/icon-naming-utils/icon-name-mapping -c mimetypes
	/usr/lib/icon-naming-utils/icon-name-mapping -c emblems
	/usr/lib/icon-naming-utils/icon-name-mapping -c panel
	/usr/lib/icon-naming-utils/icon-name-mapping -c places
	/usr/lib/icon-naming-utils/icon-name-mapping -c status
	cd /usr/share/icons/Faba/256x256/
	/usr/lib/icon-naming-utils/icon-name-mapping -c actions
	/usr/lib/icon-naming-utils/icon-name-mapping -c animations
	/usr/lib/icon-naming-utils/icon-name-mapping -c apps
	/usr/lib/icon-naming-utils/icon-name-mapping -c categories
	/usr/lib/icon-naming-utils/icon-name-mapping -c devices
	/usr/lib/icon-naming-utils/icon-name-mapping -c mimetypes
	/usr/lib/icon-naming-utils/icon-name-mapping -c emblems
	/usr/lib/icon-naming-utils/icon-name-mapping -c panel
	/usr/lib/icon-naming-utils/icon-name-mapping -c places
	/usr/lib/icon-naming-utils/icon-name-mapping -c status
	echo 'Done.'
fi

write_cache

#DEBHELPER#
